name: 'Set output runtime'
description: ''
inputs:
  _runtime:
    description: 'Current runtime (with underscore)'
    required: true
outputs:
  runtime:
    description: 'Current runtime (without underscore)'
    value: ${{ steps.setvar.outputs.envvar }}

runs:
  using: "composite"
  steps:
    - id: setvar_from
      run: |
        echo ${{ inputs._runtime }} > CI_ENV
        echo "::set-output name=envvar::$(sed -e 's/^_//' CI_ENV)"
      shell: bash
    - run: echo CURRENT_RUNTIME '${{ steps.setvar_from.outputs.envvar }}'
      shell: bash