name: bash

on: [pull_request]

jobs:
  bash:
    uses: ./.github/workflows/script-test-run.yml
    with:
      _this: ${{ env.GITHUB_JOB }}
    secrets:
      _CURRENT_RUNTIME: ${{ secrets._CURRENT_RUNTIME }}