name: Bash

on: [pull_request]

jobs:
  Bash-test-run:
    uses: ./.github/workflows/script-test-run.yml
    with:
      workflow: ${{ github.workflow }}
    secrets:
      _WORKFLOW: ${{ secrets._CURRENT_RUNTIME }}