name: example action

on: [pull_request]

jobs:
  Bash-ubuntu-host:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: var
      uses: ./.github/actions/set-output-action
      with:
        _runtime: ${{ secrets._CURRENT_RUNTIME }}
    - name: test-run
      if: ${{ steps.var.outputs.runtime == 'bash' }}
      run: ./Bash/test-run.sh