name: Python

on: [pull_request, workflow_dispatch]

jobs:
  test-run:
    uses: ./.github/workflows/script-test-run.yml
    with:
      workflow: ${{ github.workflow }}
      alpine_deps: apk add --no-cache zstd
    secrets:
      _WORKFLOW: ${{ secrets._CURRENT_RUNTIME }}