on:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
    secrets:
      _WORKFLOW:
        required: true

env:
  IMAGE_NAME: mcr.microsoft.com/windows/nanoserver:ltsc2022-amd64

jobs:
  prejob:
    runs-on: ubuntu-latest
    environment: release
    outputs:
      workflow: ${{ steps.setvar.outputs.envvar }}
    steps:
      - id: setvar
        run: |
          echo ${{ secrets._WORKFLOW }} > CI_ENV
          echo "::set-output name=envvar::$(sed -e 's/^_//' CI_ENV)"
      - run: echo "workflow:" '${{ inputs.workflow }}', "OUTPUT_WORKFLOW:" '${{ steps.setvar.outputs.envvar }}'

  ubuntu-host:
    needs: prejob
    if: ${{ needs.prejob.outputs.workflow == inputs.workflow }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test-run
      run: ./${{ inputs.workflow }}/test-run.sh