name: test-run nanoserver

on: [pull_request]

jobs:
  build:
    runs-on: windows-2022
    env:
      IMAGE_NAME: mcr.microsoft.com/windows/nanoserver:ltsc2022-amd64

    steps:
      - uses: actions/checkout@v2

      - name: pull windows container ${{ env.IMAGE_NAME }}
        shell: cmd
        run: |
          docker pull ${{ env.IMAGE_NAME }}
          docker images ${{ env.IMAGE_NAME }}

      - name: test-run
        shell: cmd
        run: >
          docker container run --rm --env CI=true -v ${{ github.workspace }}:C:\app ${{ env.IMAGE_NAME }}
          cmd /c C:\app\.tests\test-run.bat
